project:
  type: website
  output-dir: docs

website:
  title: "Découverte R - FSS"
  description: "Atelier de découverte de R - Faculté des sciences sociales, Université Laval"
  site-url: "https://etienneprx.github.io/R_decouverte_fss"
  repo-url: "https://github.com/etienneprx/R_decouverte_fss"

  navbar:
    title: "Découverte R - FSS"
    left:
      - href: index.qmd
        text: Accueil
      - href: slides.qmd
        text: Slides
    right:
      - icon: github
        href: "https://github.com/etienneprx/R_decouverte_fss"

  page-footer:
    left: "© 2026 Étienne Proulx - Université Laval"
    right:
      - icon: github
        href: "https://github.com/etienneprx/R_decouverte_fss"

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc-location: left
    code-copy: true
    code-fold: false
    fig-width: 8
    fig-height: 6

execute:
  freeze: auto
  echo: true
  warning: false
  message: false
